SHARED_LIB_DEPS =
SHARED_APP_DEPS =
STATIC_APP_DEPS =

COMMON_LOBJS	= $(COMMON_SRCS:.c=.lo)
COMMON_OBJS	= $(COMMON_SRCS:.c=.o)

ARCH_LOBJS	= $(ARCH_SRCS:.c=.lo)
ARCH_OBJS	= $(ARCH_SRCS:.c=.o)

APP_LOBJS	= $(APP_SRCS:.c=.lo)
APP_OBJS	= $(APP_SRCS:.c=.o)

SHARED_OBJS	= $(COMMON_LOBJS) $(ARCH_LOBJS)
STATIC_OBJS	= $(COMMON_OBJS)  $(ARCH_OBJS)

SHARED_LIB	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_LIB_SUFFIX)
STATIC_LIB	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_ARCHIVE_EXT)
SHARED_IMPLIB	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_IMPLIB_EXT)

APP		= $(BINDIR)/$(OS_APP_PREFIX)$(PACKAGE)$(OS_APP_SUFFIX)
DEFAULT_APP	= $(BINDIR)/$(OS_APP_PREFIX)$(PACKAGE)-default$(OS_APP_SUFFIX)
SHARED_APP	= $(BINDIR)/$(OS_APP_PREFIX)$(PACKAGE)-shared$(OS_APP_SUFFIX)
STATIC_APP	= $(BINDIR)/$(OS_APP_PREFIX)$(PACKAGE)-static$(OS_APP_SUFFIX)

CFLAGS		= $(CFLAGS_DEBUG)  $(CFLAGS_CONFIG)  $(CFLAGS_SYSROOT) \
		   $(CFLAGS_COMMON) $(CFLAGS_CMDLINE) $(CFLAGS_HOST)	\
		   $(CFLAGS_PATH) $(CFLAGS_OS) $(CFLAGS_SITE)

CFLAGS_SHARED	= $(CFLAGS) $(CFLAGS_PIC) $(CFLAGS_SHARED_ATTR)
CFLAGS_STATIC	= $(CFLAGS) $(CFLAGS_OBJ) $(CFLAGS_STATIC_ATTR)
CFLAGS_APP	= $(CFLAGS) $(CFLAGS_OBJ) $(CFLAGS_APP_ATTR)

LDFLAGS_SHARED	= $(LDFLAGS_DEBUG)   $(LDFLAGS_CONFIG)  $(LDFLAGS_SYSROOT) \
		   $(LDFLAGS_COMMON)  $(LDFLAGS_CMDLINE) $(LDFLAGS_HOST)    \
		   $(LDFLAGS_PATH)    $(SHARED_LIB_DEPS) $(LDFLAGS_LAST)

LDFLAGS_APP	= $(LDFLAGS_DEBUG)   $(LDFLAGS_CONFIG)  $(LDFLAGS_SYSROOT) \
		   $(LDFLAGS_COMMON)  $(LDFLAGS_CMDLINE) $(LDFLAGS_HOST)    \
		   $(LDFLAGS_PATH)    $(SHARED_APP_DEPS) $(LDFLAGS_LAST)

LDFLAGS_STATIC	= $(LDFLAGS_DEBUG)   $(LDFLAGS_CONFIG)  $(LDFLAGS_SYSROOT) \
		   $(LDFLAGS_COMMON)  $(LDFLAGS_CMDLINE) $(LDFLAGS_HOST)    \
		   $(LDFLAGS_PATH)    $(STATIC_APP_DEPS) $(LDFLAGS_LAST)
